@startuml


Interface IDataStorage {
get_active_data(data:int)

read_data()
save_data(data)
}

Interface IProblemSolver{
+compute_result(data) 
}

Class FileStorage {
read_data()
save_data(data)
}


Class MyApp{
Storage:FileStorage
Verifier:SudokyVerifier

get_data():List
compute_sudoku(sudoku):List

}


Class SudokuVerifier{

compute_result(data)
verify_row(sudoku):boolean, str
veirify_columns(sudoku):boolean, str
verify_quadrants(sudoku):boolean, str
is_valid_set(nums):boolean, str
is_valid_sudoku(sudoku): boolean, str

}

MyApp o-- IDataStorage
FileStorage .. IDataStorage

SudokuVerifier .. IProblemSolver
MyApp o-- IProblemSolver


@enduml